### ISSUE TITLE
[FEATURE] Add Support for SSD based instance and mount the SSDs to Opensearch data folder

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-cluster-cdk#132]
### Is your feature request related to a problem?
Currently in the CDK we only support EBS based instances with the exception of i3 instances. This limit the testing to use only EBS based cluster. With launch of Disk based vector search, we have create our own custom solutions to setup the cluster. But this repo provides a very easy way to create the cluster, hence having a capability to use SSD based instances via this CDK will be very useful.

### What solution would you like?
Ideally, we support instance  with SSD. Only by adding the nodes here: https://github.com/opensearch-project/opensearch-cluster-cdk/blob/main/lib/opensearch-config/node-config.ts#L63 won't help, we also need to mount the SSD to the correct data folder where opensearch stores the index. 
Ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/making-instance-stores-available-on-your-instances.html

### What alternatives have you considered?
Alternative is to create the setup from scratch manually.

### Do you have any additional context?
NA

**Comment by navneet1v** [comment]
@rishabh6788 what is your thoughts on this item?

**Comment by rishabh6788** [comment]
Agree, having disk based instances would benefit such use-cases. 
I can add this to our sprint, but in the meantime if you can squeeze in a PR I can review it and merge quickly.

**Comment by navneet1v** [comment]
I can give it a try, but might take some time for me to get it work. Will see if I can pick it up in upcoming week.

**Comment by rishabh6788** [comment]
The feature is available to use now.
