### ISSUE TITLE
[FEATURE] Usage of 'node.roles' instead of deprecated legacy settings for Node Bootstrapping

### ISSUE THREAD

**Issue by sandeshkr419** [opensearch-project/opensearch-cluster-cdk#16]
### Is your feature request related to a problem?
Bootstrapping nodes with legacy settings (`node.master`, `node.data`, `node.ingest`) is deprecated with OS 2.x, `node.roles` should be used instead. 
Reason being presently because of a bug in OpenSearch https://github.com/opensearch-project/OpenSearch/issues/6103, using `node.master: true` configures both `cluster_manager` and `master` role to a node, which is now being fixed and this deprecated setting will configure only deprecated `master` role only to a node instead of new `cluster_manager` to a node as `node.master` is a legacy setting. Also, `master` role will be deprecated entirely in future, which will then break usage of `node.master` entirely. 

### What solution would you like?
Use of `node.roles` with `cluster_manager` (wherever `master` role was set initially) instead of legacy settings to bootstrap nodes in https://github.com/opensearch-project/opensearch-cluster-cdk/blob/main/lib/opensearch-config/multi-node-base-config.yml for OS 2.0 and above.

### What alternatives have you considered?
Bootstrapping nodes with `node.roles`

### Do you have any additional context?
As testing out a cluster configuration, I have tried bootstrapping nodes with `cluster_manager`  and `remote_cluster_client` in `node.roles` which spins up cluster fine for OS 2.5. 

- Need to check whether we require `remote_cluster_client` role to be set additionally as `node.master` setting also sets up this role.
- Is there a plan to branch out this package separately for different OS major versions?

**Comment by rishabh6788** [comment]
The required changes have already been added by @dreamer-89. 
To make sure we don't break 1.x line as it only supports legacy settings we have created a new branch `1.x` to make sure people who want to test using 1.x line are still able to do so. 
@sandeshkr419 @bbarani

**Comment by sandeshkr419** [comment]
Great, thanks @rishabh6788 for the clarification & quick action on backward compatibility.
