### ISSUE TITLE
[FEATURE] Add support for more instance types

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-cluster-cdk#27]
### Is your feature request related to a problem?

Selection of instance types is limited by the `cpuArch` context to a specific size of Compute-Optimized instance.
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/d3b12a8774835f1a6fdf41d2ea00b8e9fb7f8b8e/lib/infra/infra-stack.ts#L86-L87

Some plugins or extensions require other instance types, such as memory optimized for Anomaly Detection HCAD (See https://github.com/opensearch-project/opensearch-sdk-java/issues/652 and https://aws.amazon.com/blogs/big-data/detect-anomalies-on-one-million-unique-entities-with-amazon-opensearch-service/)

### What solution would you like?

Allow a user to specify the instance type for each node type.

### What alternatives have you considered?

Manually changing the instance types in the `infra-stack.ts` code.

### Do you have any additional context?

Using T instance for development work costs less money while figuring things out!

See also #6

**Comment by jordarlu** [comment]
Thank you, @dbwiddis ..
@rishabh6788 will comment , and in the mean time, it will be great if you can also contribue on the changes in PR ..

**Comment by rishabh6788** [comment]
#30 PR to add more choices for data and ml nodes. @dbwiddis
