### ISSUE TITLE
[FEATURE] Add support for changing storage size of seed node

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-cluster-cdk#28]
### Is your feature request related to a problem?
The EBS volume size of seed node can't be configured and is hard-coded to 50GB:
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/d3b12a8774835f1a6fdf41d2ea00b8e9fb7f8b8e/lib/infra/infra-stack.ts#L213

When deploying a cluster with no cluster manager node, the seed node will have `data` role:
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/d3b12a8774835f1a6fdf41d2ea00b8e9fb7f8b8e/lib/opensearch-config/node-config.ts#L25

It means data will be stored evenly on the "seed" node and other data nodes. Because the storage size of other data nodes can be configured and is 100GB by default:
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/d3b12a8774835f1a6fdf41d2ea00b8e9fb7f8b8e/lib/infra/infra-stack.ts#L130

The storage size of the seed node will be a bottleneck.

### What solution would you like?
Make the EBS volume size of the seed node configurable.

### What alternatives have you considered?
n/a

### Do you have any additional context?
n/a

**Comment by jordarlu** [comment]
@rishabh6788 , pls have a review and comment.

**Comment by rishabh6788** [comment]
@tlfeng you can use `--context dataNodeStorage` to set the storage size on data node. Please let me know if that helps your case.
