### ISSUE TITLE
[FEATURE] Add support for SNAPSHOT distributions

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-cluster-cdk#29]
### Is your feature request related to a problem?

The `distributionUrl` requires the URL of a tar distribution.  The Extensions SDK is under active development including the need to test performance fixes.  When setting up clusters to test Extensions (see https://github.com/opensearch-project/opensearch-sdk-java/issues/652) there is a need to test OpenSearch from the latest Snapshot build.  These zip files are published for integration tests [here](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/distribution/integ-test-zip/opensearch/3.0.0-SNAPSHOT/)

However, the CDK hardcodes the `.tgz` filename to retrieve, and the unpacking method, here:
https://github.com/opensearch-project/opensearch-cluster-cdk/blob/b450ca4ec7185100be6b7dc7c6fcbba7c20e42e3/lib/infra/infra-stack.ts#L398-L402

### What solution would you like?

Allow a user to specify these snapshot filenames via a URL parameter. Specifically:
 - allow user to change `opensearch.tar.gz` to `opensearch-3.0.0-20230509.201738-827.zip`
 - use `unzip` rather than `tar zxf` to extract from the archive.

### What alternatives have you considered?

Using the SDK to create a cluster, and insert a script in `infra-stack.ts` to download from git version control and build the distro locally.

### Do you have any additional context?

This is probably more complicated than the brief description above.

**Comment by dbwiddis** [comment]
Disregard this request.  Found the published snapshot zips for integ testing that should suffice:
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/distribution/integ-test-zip/opensearch/3.0.0-SNAPSHOT/

**Comment by dbwiddis** [comment]
Reopening this request with edits.  The published snapshots are zip, not tgz, and have a much longer filename.

**Comment by dbwiddis** [comment]
Updating this request:
 - An acceptable workaround for SNAPSHOT is to use the nightly build
 - This is apparently already automatically done for plugins when the `distVersion` is provided
 - Suggestion is that `distributionUrl` not be required; if missing, will use the "latest" resovled from `distVersion`.
   - alternately, some text for the url such as "latest" that serves this same purpose; could also apply to the `dashboardsUrl`

**Comment by rishabh6788** [comment]
At the moment we only support tar.gz extension and nightly snapshots are also available in the same format see https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-linux-x64-latest.tar.gz. 
We also have nightly benchmark runs for 2.x and 3.x snapshots.
