### ISSUE TITLE
[FEATURE] Update 2 cluster settings that used to enable "remote store" but got changed in version 2.10

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-cluster-cdk#46]
### Is your feature request related to a problem?

A commit https://github.com/opensearch-project/OpenSearch/commit/91398c3830850ec9d48bd5dffef8d13c7b75e753 in OpenSearch repository made 2 changes in version 2.10 (and version 2.9.0 after build No.8190, though that's after the 2.9.0 release). 

Problem 1:
The cluster setting `cluster.remote_store.repository` is renamed to `cluster.remote_store.segment.repository`.
The setting is needed to use remote store feature.
https://github.com/opensearch-project/OpenSearch/commit/91398c3830850ec9d48bd5dffef8d13c7b75e753#diff-a93623446c8ee94dffd709a37ec974ee8c27f0f9f31335f35e753ed802a8dc7b 

In released version 2.9.0:
https://github.com/opensearch-project/OpenSearch/blob/2.9.0/server/src/main/java/org/opensearch/indices/IndicesService.java#L262

In current 2.x branch, which is version 2.10.0:
https://github.com/opensearch-project/OpenSearch/blob/1eea7fd6a04b0bf80d2425d59ebeadf86e650bac/server/src/main/java/org/opensearch/indices/IndicesService.java#L262

Although I created an issue in OpenSearch repository https://github.com/opensearch-project/OpenSearch/issues/8902, I closed it eventually. Changing the setting name is acceptable since the feature is under feature flag.

Problem 2:
Another setting `cluster.remote_store.translog.repository` is changed to required in the same commit. 
In the CDK script, it's fair to assign same value into `translog.repository` and above `segment.repository`.
https://github.com/opensearch-project/OpenSearch/commit/91398c3830850ec9d48bd5dffef8d13c7b75e753#diff-ea2e29ab98d6120bb1c62077f504340d6465e5178b885631170f45d209838668R986

### What solution would you like?
Add a mechanism to parse the OpenSearch version number from the String variable `opensearchVersion`, then having an `if` statement to apply to following change when OpenSearch version is equal to or above 2.10.0 .

1 Change the setting name to `cluster.remote_store.segment.repository` in the line https://github.com/opensearch-project/opensearch-cluster-cdk/blob/440fe0e1e00da98ec8c7e42281165ef09ba60358/lib/infra/infra-stack.ts#L489
2 Add `echo "cluster.remote_store.translog.repository: ${scope.stackName}-repo" >> config/opensearch.yml` around there.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
Related to the code added by PR https://github.com/opensearch-project/opensearch-cluster-cdk/pull/38

**Comment by rishabh6788** [comment]
I'll take a look at this.

**Comment by rishabh6788** [comment]
Since `remote-store` feature was not introduced in 2.9 it is safe to assume that this feature will be tested in version 2.10 and above and should be enabled for version 2.10 and above. There is no need to handle this in the code and the operator should be aware of when to enable it or not. 

Created PR https://github.com/opensearch-project/opensearch-cluster-cdk/pull/48
@tlfeng

**Comment by tlfeng** [comment]
@rishabh6788 Thank you for taking the quick action. I will close the issue.
