### ISSUE TITLE
[FEATURE] Update README / documentation on enabling remote store feature

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/opensearch-cluster-cdk#55]
### Is your feature request related to a problem?
_A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]._
Since remote store feature has been made GA in 2.10, we do not need any additional config anymore. We need to update the same. 

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by rishabh6788** [comment]
Closing as we are not running remote-store enabled runs.
