### ISSUE TITLE
[FEATURE] Support ML node instance type

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/opensearch-cluster-cdk#6]
### Is your feature request related to a problem?
We see option `mlNodeCount` for ML node count, but we don't see option to specify which EC2 instance type for ML node.

### What solution would you like?
Add one option `mlNodeInstanceType` , so we can specify different instance type to test.

### What alternatives have you considered?
No

### Do you have any additional context?
No

**Comment by rishabh6788** [comment]
As of now you can update the code [here](https://github.com/opensearch-project/opensearch-cluster-cdk/blob/main/lib/infra/infra-stack.ts#L243) to use the desired instance type. We did not add any GPU enabled instances as they are mostly not enabled by default in personal aws accounts and need to be requested, this may lead to stack deployment failure. 
We will work to at-least add those nodes as options to choose from in the code.

**Comment by laithalsaadoon** [comment]
Just checking - it looks like we would also need to at the init code to set up CUDA (nvidia) or Neuron (inf) for ML nodes, right?

**Comment by rishabh6788** [comment]
@laithalsaadoon @ylwu-amzn @tlfeng PR #30 will address this issue. Please take a look and provide your comments.

**Comment by dblock** [comment]
Looks like it was done, close?
