### ISSUE TITLE
[FEATURE] Support change admin password

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/opensearch-cluster-cdk#7]
### Is your feature request related to a problem?
I don't see how to change admin password from the readme. For security enabled cluster, the default password for `admin` is too weak (it's `admin` by default). Seems we have no way to change the default password for admin now.

### What solution would you like?
Provide some option to let user specify their own password

### What alternatives have you considered?
No

### Do you have any additional context?
No

**Comment by rishabh6788** [comment]
This feature comes from Security plugin, will go through the existing code and try to figure out if the user details can be updated at cluster setup.

**Comment by rishabh6788** [comment]
This [PR](https://github.com/opensearch-project/security/issues/3285) should address this concern as users will be able to provide the configuration using `additionalConfig` flag.
