### ISSUE TITLE
Relationship between aws-cdk-examples and this repository

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-cluster-cdk#89]
### Description
There was a recent addition to aws-cdk-examples of an OpenSearch Cluster [1].  This is great exposure for OpenSearch - is there a way this repo should be connected to aws-cdk-examples?

### Related
- [1] https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/opensearch

**Comment by gaiksaya** [comment]
Hi @peternied ,

I believe the examples mentioned in the above repository was based on aws cdk modules for specific service. Example: S3, AWS OpenSearch. 
However, this repository holds the cdk code base to deploy opensource opensearch-project artifacts. Right now it has nothing to do with AWS OpenSearch Service. To give you a gist, it downloads the tarball for given version and installs OpenSearch on EC2. In case of multinode cluster, each EC2 is a type of node in the cluster example manager node, data node, ml node, etc.

Hope this answers your question.

**Comment by gaiksaya** [comment]
Closing this issue, Please re-open if needed.
Thanks!
